package clickMove;

import java.awt.Image;

import javax.swing.ImageIcon;

public class ImgLoad {
	public static Image[] play;
	public static Image[] tile;
	public static Image[] txtMc;
	public static Image[] health;
	public static Image[] wallAr;
	public static Image[] groundAr;
	public static Image[] small;
	public static Image[] invItems;
	public static Image[] runeScape;
	public static Image[] txtAr;

	public static void imageInit() {
		int a = 0;

		play = new Image[9];
		ImageIcon ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/Cylinder.png"));
		play[0] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderN.png"));
		play[1] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderE.png"));
		play[2] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderS.png"));
		play[3] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderW.png"));
		play[4] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderNW.png"));
		play[5] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderNE.png"));
		play[6] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderSE.png"));
		play[7] = ii.getImage();
		ii = new ImageIcon(
				ImgLoad.class.getResource("res/Cylinder/CylinderSW.png"));
		play[8] = ii.getImage();

		tile = new Image[1];
		ii = new ImageIcon(ImgLoad.class.getResource("res/TGrassL.png"));
		tile[0] = ii.getImage();

		txtMc = new Image[38];
		a = 0;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cA.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cB.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cC.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cD.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cE.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cF.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cG.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cH.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cI.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cJ.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cK.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cL.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cM.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cN.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cO.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cP.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cQ.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cR.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cS.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cT.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cU.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cV.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cW.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cX.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cY.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cZ.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/cSpace.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n0.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n1.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n2.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n3.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n4.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n5.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n6.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n7.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n8.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/n9.png"));
		txtMc[a] = ii.getImage();
		a += 1;
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/mc/period.png"));
		txtMc[a] = ii.getImage();
		a += 1;

		txtAr = new Image[43];
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cA.png"));
		txtAr[0] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cB.png"));
		txtAr[1] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cC.png"));
		txtAr[2] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cD.png"));
		txtAr[3] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cE.png"));
		txtAr[4] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cF.png"));
		txtAr[5] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cG.png"));
		txtAr[6] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cH.png"));
		txtAr[7] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cI.png"));
		txtAr[8] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cJ.png"));
		txtAr[9] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cK.png"));
		txtAr[10] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cL.png"));
		txtAr[11] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cM.png"));
		txtAr[12] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cN.png"));
		txtAr[13] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cO.png"));
		txtAr[14] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cP.png"));
		txtAr[15] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cQ.png"));
		txtAr[16] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cR.png"));
		txtAr[17] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cS.png"));
		txtAr[18] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cT.png"));
		txtAr[19] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cU.png"));
		txtAr[20] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cV.png"));
		txtAr[21] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cW.png"));
		txtAr[22] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cX.png"));
		txtAr[23] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cY.png"));
		txtAr[24] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cZ.png"));
		txtAr[25] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/cSpace.png"));
		txtAr[26] = ii.getImage();

		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n0.png"));
		txtAr[27] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n1.png"));
		txtAr[28] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n2.png"));
		txtAr[29] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n3.png"));
		txtAr[30] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n4.png"));
		txtAr[31] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n5.png"));
		txtAr[32] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n6.png"));
		txtAr[33] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n7.png"));
		txtAr[34] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n8.png"));
		txtAr[35] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/n9.png"));
		txtAr[36] = ii.getImage();

		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/slash.png"));
		txtAr[37] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/qMark.png"));
		txtAr[38] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/qMarkI.png"));
		txtAr[39] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/(.png"));
		txtAr[40] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/).png"));
		txtAr[41] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Text/tx/underscore.png"));
		txtAr[42] = ii.getImage();

		health = new Image[25];
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h0.png"));
		health[0] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h1.png"));
		health[1] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h2.png"));
		health[2] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h3.png"));
		health[3] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h4.png"));
		health[4] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h5.png"));
		health[5] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h6.png"));
		health[6] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h7.png"));
		health[7] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h8.png"));
		health[8] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h9.png"));
		health[9] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h10.png"));
		health[10] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h11.png"));
		health[11] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h12.png"));
		health[12] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h13.png"));
		health[13] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h14.png"));
		health[14] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h15.png"));
		health[15] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h16.png"));
		health[16] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h17.png"));
		health[17] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h18.png"));
		health[18] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h19.png"));
		health[19] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h20.png"));
		health[20] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h21.png"));
		health[21] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h22.png"));
		health[22] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h23.png"));
		health[23] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Health/h24.png"));
		health[24] = ii.getImage();

		groundAr = new Image[5];
		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/TGrassL.png"));
		groundAr[0] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/Water1.png"));
		groundAr[1] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/Water2.png"));
		groundAr[2] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/RuneScape/Grey.png"));
		groundAr[3] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/RuneScape/LightGrey.png"));
		groundAr[4] = ii.getImage();

		wallAr = new Image[30];
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/North.png"));
		wallAr[1] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/East.png"));
		wallAr[2] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/South.png"));
		wallAr[3] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/West.png"));
		wallAr[4] = ii.getImage();

		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/CornerNE.png"));
		wallAr[5] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/CornerNW.png"));
		wallAr[6] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/CornerSE.png"));
		wallAr[7] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/CornerSW.png"));
		wallAr[8] = ii.getImage();

		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/SWDiag.png"));
		wallAr[9] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/NEDiag.png"));
		wallAr[10] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/NWDiag.png"));
		wallAr[11] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/SEDiag.png"));
		wallAr[12] = ii.getImage();

		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/NEEdge.png"));
		wallAr[13] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/SEEdge.png"));
		wallAr[14] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/SWEdge.png"));
		wallAr[15] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/NWEdge.png"));
		wallAr[16] = ii.getImage();
		
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorNE.png"));
		wallAr[17] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorEN.png"));
		wallAr[18] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorES.png"));
		wallAr[19] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorSE.png"));
		wallAr[20] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorSW.png"));
		wallAr[21] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorWS.png"));
		wallAr[22] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorWN.png"));
		wallAr[23] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/FlatWall/DoorNW.png"));
		wallAr[24] = ii.getImage();

		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/TBush1.png"));
		wallAr[25] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/Wall/Wall2.png"));
		wallAr[26] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Tile/Fire.png"));
		wallAr[27] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Nodes/CopperOre.png"));
		wallAr[28] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Nodes/CopperOreEmpty.png"));
		wallAr[29] = ii.getImage();
		
		small = new Image[3];
		ii = new ImageIcon(ImgLoad.class.getResource("res/Cylinder/Outline.png"));
		small[0] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/NuI.png"));
		small[1] = ii.getImage();
		ii = new ImageIcon(ImgLoad.class.getResource("res/Moneybag.png"));
		small[2] = ii.getImage();

		invItems = new Image[2];
		ii = new ImageIcon(ImgLoad.class.getResource("res/Moneybag.png"));
		invItems[1] = ii.getImage();

		// runeScape = new Image[2];

	}
}
